# Generated by Django 5.1.7 on 2025-03-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
