# Generated by Django 4.2.1 on 2024-11-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_transaction_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
    ]
