# Generated by Django 4.2.1 on 2024-11-23 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_transaction_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('Уход', 'Приход'), ('Уход', 'Уход')], max_length=10, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='count',
            field=models.CharField(max_length=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт'),
        ),
    ]
