# Generated by Django 4.2.1 on 2024-11-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_count_alter_transaction_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_price',
            field=models.FloatField(default=0, verbose_name='Средняя цена'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
