# Generated by Django 4.2.1 on 2024-12-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_average_price_alter_transaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Общая количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество на текущий момент'),
        ),
    ]
