# Generated by Django 4.2.1 on 2024-12-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_in_stok_product_out_of_stok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='out_of_stok',
        ),
    ]
