# Generated by Django 4.2.1 on 2024-12-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_out_of_stok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stok',
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3, verbose_name='В наличии'),
        ),
    ]
