# Generated by Django 4.2.1 on 2024-12-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_in_stok_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3, verbose_name='Опубликовано'),
        ),
    ]
