# Generated by Django 4.2.1 on 2024-12-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_public',
            new_name='is_publiched',
        ),
    ]
