# Generated by Django 4.2.1 on 2024-12-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productphoto',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
